### ISSUE TITLE
Pyrotech: TreeMap blocked, doesn't cause crash but seems like it should be allowed

### ISSUE THREAD

**Issue by H-QueerCoded** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#11]
Singleplayer
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12214114/latest.log)

**Comment by Semisol** [comment]
Could you also try with the option specified in #8 to see what else would get blocked?

**Comment by H-QueerCoded** [comment]
https://mclo.gs/YdkYh5K

**Comment by Semisol** [comment]
okay, should work now without the option
