### ISSUE TITLE
[Exclusion] Project Ozone

### ISSUE THREAD

**Issue by camperboy1000** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#12]
**Do you play in singleplayer or multiplayer?**
- [x] Singleplayer
- [ ] Multiplayer

**What modpacks or mods you use**
Project Ozone (1.7.10)

**Game log files**
https://mclo.gs/fwlI1pT

It looks like SimpleAchievements is the culprit given lines 5774 and 5775.

**Comment by Semisol** [comment]
I'll look into it soon. Not sure why it is showing java.lang.Enum instead of the underlying enum class

**Comment by Semisol** [comment]
Solved by 1.1.3
