### ISSUE TITLE
MixinBooter mod

### ISSUE THREAD

**Issue by AechtRob** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#19]
I think that the common mod https://www.curseforge.com/minecraft/mc-mods/mixin-booter uses the ObjectInputStream in its UnsafeAllocator.java class file in the latest version 8.3

**Comment by Rongmario** [comment]
Mixin packs Gson as part of their library, which includes `UnsafeAllocator`. Though also, it is part of Minecraft's dependencies anyway. `Gson` is from Google. Not MixinBooter.

**Comment by xyzeva** [comment]
All usages of ObjectInputStream are not vulnerable. As said by the author of the plugin @Rongmario, this class is actually from GSON, and GSON does not have such vulnerability.
