### ISSUE TITLE
ClassNotFoundException crash on startup 1.12

### ISSUE THREAD

**Issue by H-QueerCoded** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#4]
Happens with both 1.1.0 and 1.1.1
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12208223/latest.log)

**Comment by quentin452** [comment]
i have the same issue , it seem the issue appear when adding mixinbooter and an another mod.
For my experience i got the same issue when using mixinbioter + essentials + pipeblocker

**Comment by Semisol** [comment]
What java version are you launching it with?

**Comment by quentin452** [comment]
java 8 ,1.12.2

**Comment by quentin452** [comment]
i don't think you can launch 1.12.2 with java 9+

**Comment by Semisol** [comment]
> i don't think you can launch 1.12.2 with java 9+

yeah, forget that

> java 8 ,1.12.2

I think your launcher is using an older java 8 version, if you could, could you try installing Java 8 and using that instead of what comes with the launcher? (I don't think the vanilla launcher allows changing the JRE)

**Comment by quentin452** [comment]
i use zulu8.70.0.23 , so i think its already updated , and polymc, windows 10

**Comment by Semisol** [comment]
> i have the same issue , it seem the issue appear when adding mixinbooter and an another mod. For my experience i got the same issue when using mixinbioter + essentials + pipeblocker

could you send your latest.log?

**Comment by quentin452** [comment]
yes i will send to you

**Comment by quentin452** [comment]
https://mclo.gs/1oEYS6F

**Comment by Semisol** [comment]
@quentin452 looks like you have another mod overwriting the filter used by pipeblocker. looks like this approach isn't the best

**Comment by quentin452** [comment]
hum

**Comment by AzureAqua** [comment]
Try updating mixinbooter, I believe this issue occurs as Essential reloads the game when older mixin versions are detected, so using the newer mixin versions should stop the reload which I think is causing the filters to be registered twice

**Comment by quentin452** [comment]
it seem that the issue is fixed by updating mixinbooter , thx but mixinbotter 8.0+ have some issues with other mods so i am blocked

**Comment by H-QueerCoded** [comment]
I was able to fix my issue by switching to a more recent release of Java 8 (1.8.0_301 instead of 1.8.0_51)
The vanilla launcher does allow changing JRE
I was already using the most recent version of mixinbooter
