### ISSUE TITLE
It seems singleplayer worlds are un-enter-able with this mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#9]
Title. Any new or current world will kick you. The SerializationIsBad mod seems to work just fine.

![2023-07-30_14 44 08](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/assets/51277766/b8e68073-daea-4335-a68e-0d62da861747)

[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12210097/latest.log)
[fml-client-latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12210098/fml-client-latest.log)

**Comment by Semisol** [comment]
Please follow the process in #8 `InvalidClassException: filter status: REJECTED` and then post your log file from that too, if you can.

**Comment by MagmaSlime123** [comment]
I posted both log files above.

**Comment by Semisol** [comment]
> I posted both log files above.

Can you try using the option specified in #8 and then send your logs? `-Dinfo.mmpa.pipeblocker.log-only=true` (remove it after you send your logs)

**Comment by MagmaSlime123** [comment]
https://pastebin.com/EMnN7Zk2

Found several mod rejection things in here.

[fml-client-latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12210161/fml-client-latest.log)
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12210162/latest.log)

**Comment by Semisol** [comment]
Please update your PipeBlocker version to 1.1.2 and redo the steps with the startup options. If it's still broken, feel free to reply and I'll reopen this.

**Comment by xyzeva** [comment]
This is fixed at version 1.1.2 as mentioned above.

**Comment by MagmaSlime123** [comment]
I had the option enabled when I provided those logs.

It seems 1.1.2 fixed this though.
